print("haliho!")
print("gsdhjfgsdh")
print("Dominik2") 
print("kettő")
print("Dominik")
print("valami")
print("Alfréd")
print("Miki")
print("Új sor")
print("Ricsi")
print("test")
print("szilasi")
print("alma")
print("körte")
print("répa")
