print("haliho!")
print("gsdhjfgsdh")
print("Dominik2") 
print("kettő")
print("Dominik")
print("valami")
print("Alfréd")
print("Miki")
print("Új sor")
print("Ricsi")
print("test")
print("Ricsi 2026.02.03")
print('Miki 2026.02.03')
